### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by mimipeshy** [Miguelus373/Ruby-Tic-Tac-Toe#6]
Hi Carlos and Miguel
You guys have done an amazing job with the tic-tac-toe project, its very clean and efficient, Kudos for that. We wish you all the best in your next project

Kind Regards
#team-122-the-manx

**Comment by carlos-ssh** [comment]
Thank you Peris for your words and your wishes! 

Let's keep coding! 🥇

**Comment by eliasecasta** [comment]
WAAAAAAAAAARM!

**Comment by carlos-ssh** [comment]
@e71az HAHAHAHAH
